services:
  - type: web
    name: rage-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: JWT_SECRET
        value: 4ff79ebb28d08e65eb969e42266e063d7414420c74d21e6b0499d5aa3ff1fc38
      - key: MONGO_URI
        sync: false
